// CYBER MINI PACK string table [zh-HK, en]
import { i18n } from 'cyber-kit';
i18n.add({
  'doc.title': ['賽博小遊戲 CYBER MINI PACK · 包剪揼 · 過三關 · 神經反射', 'CYBER MINI PACK · Rock Paper Scissors · Tic-Tac-Toe · Reaction'],
  kicker: ['NEON KOWLOON · 街機角落', 'NEON KOWLOON · ARCADE CORNER'], title: ['賽博小遊戲', 'MINI PACK'], titleEn: ['CYBER MINI PACK', 'CYBER ARCADE TRIO'],
  tagline: ['三款經典街頭小遊戲，一部機玩晒。全部都係無盡挑戰 —— 揀一款開始：', 'Three street classics in one machine — every mode is an endless challenge. Pick one:'],
  'm.rps': ['包剪揼', 'ROCK PAPER SCISSORS'], 'm.rpsS': ['ROCK · PAPER · SCISSORS', '包剪揼'], 'm.xo': ['過三關', 'TIC-TAC-TOE'], 'm.xoS': ['TIC-TAC-TOE LADDER', '過三關'],
  'm.react': ['神經反射', 'REACTION TEST'], 'm.reactS': ['REACTION TEST', '神經反射'],
  'mc.rps': ['最佳連勝 {n} · 無盡 AI 對手', 'Best streak {n} · endless AI rivals'], 'mc.xo': ['最遠第 {n} 關 · 無盡關卡', 'Best stage {n} · endless stages'],
  'mc.react': ['最佳平均 {ms} ms · 最高第 {r} 輪', 'Best avg {ms} ms · best round {r}'], 'mc.reactNew': ['綠燈一著即撳 · 一輪比一輪快', 'Tap on green · every round gets faster'],
  privacy: ['私隱政策', 'Privacy policy'], backTip: ['返回選單 (Esc)', 'Mode select (Esc)'], muteTip: ['靜音 (M)', 'Mute (M)'],
  rock: ['揼', 'ROCK'], paper: ['包', 'PAPER'], scissors: ['剪', 'SCISSORS'], rockS: ['ROCK · 1', '1'], paperS: ['PAPER · 2', '2'], scissorsS: ['SCISSORS · 3', '3'],
  undo: ['悔棋', 'UNDO'], undoS: ['UNDO · Z', 'Z'],
  paused: ['已暫停', 'PAUSED'], pausedS: ['PAUSED', '已暫停'], resume: ['繼續', 'RESUME'], resumeS: ['RESUME · P', 'P'], modes: ['返回選單', 'MODE SELECT'], modesS: ['MODE SELECT', 'ESC'],
  keepStreak: ['保住連勝', 'KEEP STREAK'], keepStreakN: ['保住 {n} 連勝', 'KEEP {n}-STREAK'], viaAd: ['睇段廣告', 'WATCH AD'], free: ['免費', 'FREE'],
  vs: ['VS {name}', 'VS {name}'], streak: ['連勝', 'STREAK'], stage: ['關卡', 'STAGE'], best: ['最佳', 'BEST'], round: ['輪數', 'ROUND'],
  oppN: ['對手 {n}', 'RIVAL {n}'], bestOf: ['{n} 局 {w} 勝', 'FIRST TO {w}'], beats1: ['包', 'PAPER'], beats2: ['剪', 'SCISSORS'], beats3: ['揼！', 'ROCK!'],
  draw: ['和！ {p} vs {a}', 'DRAW! {p} vs {a}'], point: ['{p} 贏 {a}！', '{p} beats {a}!'], aiPoint: ['{a} 贏 {p}…', '{a} beats {p}…'], again: ['再嚟！揀一樣', 'Again! Choose'],
  win: ['你贏咗！', 'YOU WIN!'], lose: ['輸咗…', 'YOU LOSE…'], score: ['比分', 'Score'], bestStreak: ['最佳連勝', 'Best streak'], rival: ['對手', 'Rival'],
  nextRival: ['下一位對手', 'NEXT RIVAL'], rematch: ['再挑戰', 'REMATCH'], enter: ['ENTER', 'ENTER'],
  milestone: ['里程碑！', 'MILESTONE!'], milestoneRps: ['連闖 {n} 位對手', '{n} rivals beaten'], endlessOn: ['無盡模式', 'ENDLESS'],
  stageN: ['第 {n} 關', 'STAGE {n}'], aiFirst: ['對手先行…', 'AI goes first…'], youFirst: ['你先行', 'Your move'], thinking: ['對手諗緊…', 'Thinking…'], yourMove: ['到你', 'Your move'],
  undone: ['已悔棋', 'Undone'], noUndo: ['未有得悔棋', 'Nothing to undo'], undoAdT: ['悔多一步？', 'One more undo?'], undoAdTxt: ['睇一段自願觀看嘅獎勵廣告。', 'Watch an optional rewarded ad.'],
  undoWebT: ['悔多一步', 'One more undo'], undoWebTxt: ['網頁版免費。(App 版會用自願觀看嘅獎勵廣告。)', 'Free on the web. (The app uses an optional rewarded ad.)'], watchAd: ['睇廣告', 'WATCH AD'], claim: ['領取', 'CLAIM'],
  youO: ['✕ 你 · ◯ AI', '✕ YOU · ◯ AI'], held: ['頂住主機！', 'HELD THE CORE!'], cleared: ['過關！', 'STAGE CLEAR!'], xoDraw: ['和局', 'DRAW'],
  result: ['結果', 'Result'], rWin: ['勝', 'WIN'], rDraw: ['和', 'DRAW'], rLoss: ['負', 'LOSS'], moves: ['步數', 'Moves'], bestStage: ['最遠關卡', 'Best stage'], winBonus: ['擊敗核心', 'Core beaten'],
  nextStage: ['下一關', 'NEXT STAGE'], replay: ['再嚟一局', 'REPLAY'],
  ready: ['準備好未？', 'Ready?'], tryN: ['第 {n} 次', 'Try {n}'], wait: ['等綠燈…', 'Wait for green…'], go: ['撳！', 'TAP!'], falseStart: ['偷步！', 'FALSE START!'],
  roundN: ['第 {n} 輪', 'ROUND {n}'], target: ['目標平均 < {ms} ms', 'Target avg < {ms} ms'], passed: ['過關！下一輪更快', 'Passed! Next round is faster'],
  avg: ['平均', 'Average'], fastest: ['最快', 'Fastest'], fouls: ['偷步', 'False starts'], bestAvg: ['最佳紀錄', 'Best avg'], roundReached: ['到達輪數', 'Round reached'],
  nextRound: ['下一輪', 'NEXT ROUND'], tryAgain: ['再測一次', 'TRY AGAIN'], needCoffee: ['要再試過', 'TRY AGAIN'], gauntletOver: ['挑戰結束', 'GAUNTLET OVER'],
  'tier.0': ['神經超頻', 'OVERCLOCKED'], 'tier.1': ['賽博反射', 'CYBER REFLEX'], 'tier.2': ['快過的士', 'FASTER THAN A TAXI'], 'tier.3': ['正常人類', 'HUMAN'], 'tier.4': ['要飲杯咖啡', 'NEEDS COFFEE'],
  streakSaved: ['連勝保住咗：{n}', 'Streak saved: {n}'], fatal: ['載入失敗', 'Failed to start'],
});
